trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    displayName: "Use Python 3"
    inputs:
      versionSpec: "3.x"
      addToPath: true
      architecture: "x64"
  - script: |
      python -m pip install --upgrade pip
      pip install yamllint
    displayName: "Install dependencies"
  - script: yamllint . --no-warnings
    displayName: "Lint all yaml files"
